### PR TITLE
Add support for UXT*/SXT* Thumb instructions

### PR DESCRIPTION
**Pull request by nshp**
Starting small to see how this goes, plus I don't know how to run your tests yet!

### CODE REVIEW

**Comment by psifertex** [comment]
Do you happen to have some test cases we can use to test the new instructions?

**Comment by psifertex** [comment]
Also, congrats on first PR! Here's to hoping it's the first accepted PR. 😉 

🥇

**Comment by nshp** [comment]
Do you folks have some established framework for lifter testing I should add to? Should I just drop some instructions (text? bytes?) and the lifted IL I expect from them here in the PR comments?

**Comment by nshp** [comment]
Fixed a bug in my addition there -- I'd assumed `instr->fields` was zero-initialized, but I noticed it is not. Instead there's a `fields_mask` which indicates which fields are actually present in the instruction.

Just sort of spewing notes as I go so we can perhaps make a contributing guide. :smile:

**Comment by lwerdna** [comment]
@nshp thanks for the pull request, looks straightforward, let me get some tests running and then I'll get your code in

**Comment by ehntoo** [comment]
I had picked the exact same instructions to implement as a first commit but hadn't looked at github since first thing this morning. :smile: I think your implementation is definitely preferable to mine anyway. https://github.com/ehntoo/arch-armv7/commit/22591311d077fd19caf5a80a65aef59197a066c7

**Comment by lwerdna** [comment]
@nshp here's some improved analysis after your implementation:

Screen Shot 2020-10-08 at 6 28 08 PM

(after on left, before on right)

**Pull request merged**
